apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
spec:
    project: default
    source:
      repoURL: 'https://raw.githubusercontent.com/at9169/HELM/gh-pages/'
      targetRevision: 9.3.0
      chart: mysql
    destination:
      server: 'https://kubernetes.default.svc'
      namespace: mysql
    syncPolicy:
      syncOptions:
        - CreateNamespace=true